site_name: FitNotes Documentation
theme: readthedocs
markdown_extensions:
    - admonition

nav:
- Home: 'index.md'
- Workouts: 'workouts.md'
- Exercises: 'exercises.md'
- Logs: 'logs.md'
- Settings: 'settings.md'
- Manage Your Data: 'data.md'
- Release Notes: 'release-notes.md'